services:

  # Nginx service
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro   # Nginx conf folder
      - ./nginx/log/:/var/log/nginx:rw        # Log folder
      - ./certbot/www/:/var/www/certbot/:ro   # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:ro  # Certbot folder
    networks:
      - local-net
    depends_on:
      - jenkins   # Need to know jenkins host for reverse proxy

  # Lets Encrypt service
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw   # Certbot challenge folder
      - ./certbot/conf/:/etc/letsencrypt/:rw  # Certbot etc folder
    depends_on:
      - webserver # Need webserver to run

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    volumes:
      - ./jenkins/config/:/var/jenkins_home:rw # Jenkins config folder
    networks:
      - local-net

  # Hugo service
  hugo:
    image: hugo/hugo
    build: ./hugo

networks:
  local-net:
